name: Genshin Impact Helper Global

on:
  schedule:
      - cron: "59 19 * * *"
  
  workflow_dispatch:
env:
  RUN_ENV: 'prod'

jobs:

  build:
 
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout master
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
